version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Building complete"
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  version: 2
  # This runs on non-tag pushes
  untagged-build:
    jobs:
      - build
  # This only runs on deploy tags and not branches
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /beta*/
      - test:
          filters:
            tags:
              only: /beta*/
          requires:
            - build
      - deploy:
          filters:
            tags:
              only: /beta*/
          requires:
            - test
