version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.1

jobs:
  build:
    docker:
    - image: cimg/node:lts-browsers

    parameters:
      webpack_stats_path:
        type: string
        default: /tmp/artifacts/groening-webpack-stats-<< pipeline.number >>.json

    steps:
        - run:
            name: Creating Dummy Artifacts
            command: |
              echo "my artifact file" > /tmp/art-1;
              mkdir /tmp/artifacts;
              echo "my artifact files in a dir" > /tmp/artifacts/art-2;
              echo "my artifact files in a dir" > /tmp/artifacts/groening-webpack-stats-110.json;
        - store_artifacts:
            path: /tmp/art-1
            destination: artifact-file
        - store_artifacts:
            path: /tmp/artifacts
        - store_artifacts:
            path: << parameters.webpack_stats_path >>
        - store_artifacts:
            path: /tmp/artifacts/groening-webpack-stats-<< pipeline.number >>.json
        - store_artifacts:
            path: /tmp/artifacts/groening-webpack-stats-110.json
        - store_artifacts:
            path: /tmp/artifacts/groening-webpack-stats-110

workflows:
  build:
    jobs:
      - build