version: 2.1

orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - run: echo "Ruby 2.7 has been installed"

workflows:
  run-jobs:
    jobs:
      - build
