version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.1

jobs:
  build:
    parameters:
      webpack_stats_path:
        type: string
        default: /home/circleci/artifact_testing-<< pipeline.number >>.json

    docker:
    - image: cimg/node:lts-browsers
    working_directory: /tmp
    steps:
    - run:
        name: Creating Dummy Artifacts
        command: |
          echo "my artifact file" > /home/circleci/example.txt;

    - run:
        command: mkdir -p ~/artifact_testing

    - store_artifacts:
          path: ~/artifact_testing/artifact_testing.json

    - store_artifacts:
          path: ~/artifact_testing/artifact_testing-<< pipeline.number >>.json

workflows:
  build:
    jobs:
      - build