version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Building complete"
      - run: ls ~/tmp 
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
  test:
    docker:
      - image: circleci/node
    steps:
      - run: echo "Testing complete"
  deploy:
      docker:
        - image: circleci/node
      steps:
        - run: echo "DEPLOYING" # Make sure tests pass first!
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test
      - deploy