version: 2.1
jobs:
  build:
    parameters:
      webpack_stats_path:
        type: string
        default: /home/circleci/artifact_testing-<< pipeline.number >>.json

    docker:
    - image: linux
    working_directory: /tmp
    steps:
    - store_artifacts:
          path: << parameters.webpack_stats_path >>
          destination: /

workflows:
  build:
    jobs:
      - build